version: "3.9"
services:
  nfs_server:
    image: itsthenetwork/nfs-server-alpine
    container_name: nfs_server
    restart: unless-stopped
    privileged: true
    environment:
      - SHARED_DIRECTORY=/data
    ports:
      - "2049:2049"
    volumes:
      - ${PWD}/server_nfs/data_nfs:/data
    networks:
      nfs_server_network:
        ipv4_address: 172.19.99.2
  client_server1:
    privileged: true
    container_name: client_server1
    build:
      context: ./server_client
      dockerfile: Dockerfile-server
    ports:
      - "8085:80"
    depends_on:
      - nfs_server
    networks:
      nfs_server_network:
        ipv4_address: 172.19.99.3
  client_server2:
    privileged: true
    container_name: client_server2
    build:
      context: ./server_client
      dockerfile: Dockerfile-server
    ports:
      - "8086:80"
    depends_on:
      - nfs_server
    networks:
      nfs_server_network:
        ipv4_address: 172.19.99.4
networks:
  nfs_server_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.99.0/24
          gateway: 172.19.99.1
