FROM		ubuntu:14.04
MAINTAINER	"Thomas Jeong <unistommy@gmail.com>"
LABEL		"purpose"="NFS Server Demo"
COPY		./requirements.txt /requirements.txt
RUN		apt-get update && apt-get -y install nfs-kernel-server nfs-common && \
		apt-get clean -y && \
		apt-get autoremove -y && \
		rm -rfv /tmp/* /var/lib/at/lists/* /var/tmp/*
EXPOSE		80
CMD		["bin/bash"]
